# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "git-id"

[variables]
CMAKE_EXPORT_COMPILE_COMMANDS = true

[target.git-id]
type = "executable" # static, shared
sources = ["src/**.cpp", "src/**.hpp"]
compile-features = ["cxx_std_23"]
